# Copyright (c) 2022 Graphcore Ltd. All rights reserved.
---
exclude: |
  (?x)^(
      .arcconfig|
      .*\.gitignore|
      utils/linters/codespell_ignore.txt
  )$
repos:
  - repo: local
    hooks:
      - id: copyright-linter
        name: Copyright linter
        description: Ensures that files have the proper copyright line.
        entry: python3 -m utils.lint.linters.copyright_linter
        language: python
        exclude: |
          (?x)^(
            .*\.txt|
            .*\.json|
            .*\.jp(e?)g|
            .*\.png|
            .*\.pth|
            .*\.ini|
            .*Makefile|
            .*ipynb|
            .*LICENSE|
            .*COPYRIGHT
          )$
        additional_dependencies:
          # dataclasses was introduced in Python 3.7
          # For python 3.6 it therefore needs to be added as a dependency
          - dataclasses
          - GitPython
      - id: url-linter
        name: URL linter
        description: Ensures that URLs in files are correct.
        entry: python3 -m utils.lint.linters.url_linter
        language: python
        require_serial: true
        files: |
          (?x)^(
              .+\.txt|
              .+\.md|
              .*\.ipynb|
              .*\.rst
          )$
        additional_dependencies:
          - requests
      - id: fstring-linter
        name: f-string linter
        description: Ensures that we use Python 3.6 f-strings over .format().
        entry: python3 -m utils.lint.linters.fstring_linter
        language: python
        require_serial: true
        files: (?x).*\.py$
      - id: pytest-linter
        name: Pytest linter
        description: Ensures that tests use Pytest (not unittest or SubProcessChecker).
        entry: python3 -m utils.lint.linters.pytest_linter
        language: python
        require_serial: true
        files: (?x).*\.py$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      # Install with pip3 install clang-format==9.0.0
      - id: clang-format
        args: [
            -i, # Fix inplace
            --style=file, # Use .clang-tidy
          ]
